// Code generated by MockGen. DO NOT EDIT.
// Source: repository/google_sign_in_api_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/MapMinder/mapminder_backend/feature/auth/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockGoogleSignInApiRepository is a mock of GoogleSignInApiRepository interface.
type MockGoogleSignInApiRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGoogleSignInApiRepositoryMockRecorder
}

// MockGoogleSignInApiRepositoryMockRecorder is the mock recorder for MockGoogleSignInApiRepository.
type MockGoogleSignInApiRepositoryMockRecorder struct {
	mock *MockGoogleSignInApiRepository
}

// NewMockGoogleSignInApiRepository creates a new mock instance.
func NewMockGoogleSignInApiRepository(ctrl *gomock.Controller) *MockGoogleSignInApiRepository {
	mock := &MockGoogleSignInApiRepository{ctrl: ctrl}
	mock.recorder = &MockGoogleSignInApiRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoogleSignInApiRepository) EXPECT() *MockGoogleSignInApiRepositoryMockRecorder {
	return m.recorder
}

// GetGoogleUserInfo mocks base method.
func (m *MockGoogleSignInApiRepository) GetGoogleUserInfo(ctx context.Context, googleSignInCreds domain.GoogleSignInCreds) (domain.GoogleIdToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGoogleUserInfo", ctx, googleSignInCreds)
	ret0, _ := ret[0].(domain.GoogleIdToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGoogleUserInfo indicates an expected call of GetGoogleUserInfo.
func (mr *MockGoogleSignInApiRepositoryMockRecorder) GetGoogleUserInfo(ctx, googleSignInCreds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGoogleUserInfo", reflect.TypeOf((*MockGoogleSignInApiRepository)(nil).GetGoogleUserInfo), ctx, googleSignInCreds)
}
