// Code generated by MockGen. DO NOT EDIT.
// Source: repository/oauth_tokens_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/MapMinder/mapminder_backend/feature/auth/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockOauthTokenRepository is a mock of OauthTokenRepository interface.
type MockOauthTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOauthTokenRepositoryMockRecorder
}

// MockOauthTokenRepositoryMockRecorder is the mock recorder for MockOauthTokenRepository.
type MockOauthTokenRepositoryMockRecorder struct {
	mock *MockOauthTokenRepository
}

// NewMockOauthTokenRepository creates a new mock instance.
func NewMockOauthTokenRepository(ctrl *gomock.Controller) *MockOauthTokenRepository {
	mock := &MockOauthTokenRepository{ctrl: ctrl}
	mock.recorder = &MockOauthTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOauthTokenRepository) EXPECT() *MockOauthTokenRepositoryMockRecorder {
	return m.recorder
}

// CreateOauthToken mocks base method.
func (m *MockOauthTokenRepository) CreateOauthToken(ctx context.Context, oauthToken domain.OauthToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOauthToken", ctx, oauthToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOauthToken indicates an expected call of CreateOauthToken.
func (mr *MockOauthTokenRepositoryMockRecorder) CreateOauthToken(ctx, oauthToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOauthToken", reflect.TypeOf((*MockOauthTokenRepository)(nil).CreateOauthToken), ctx, oauthToken)
}

// GetOauthInformation mocks base method.
func (m *MockOauthTokenRepository) GetOauthInformation(ctx context.Context, sub string) (domain.OauthToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOauthInformation", ctx, sub)
	ret0, _ := ret[0].(domain.OauthToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOauthInformation indicates an expected call of GetOauthInformation.
func (mr *MockOauthTokenRepositoryMockRecorder) GetOauthInformation(ctx, sub interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOauthInformation", reflect.TypeOf((*MockOauthTokenRepository)(nil).GetOauthInformation), ctx, sub)
}
