// Code generated by MockGen. DO NOT EDIT.
// Source: repository/reminder_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/MapMinder/mapminder_backend/feature/reminder/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockReminderRepository is a mock of ReminderRepository interface.
type MockReminderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReminderRepositoryMockRecorder
}

// MockReminderRepositoryMockRecorder is the mock recorder for MockReminderRepository.
type MockReminderRepositoryMockRecorder struct {
	mock *MockReminderRepository
}

// NewMockReminderRepository creates a new mock instance.
func NewMockReminderRepository(ctrl *gomock.Controller) *MockReminderRepository {
	mock := &MockReminderRepository{ctrl: ctrl}
	mock.recorder = &MockReminderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReminderRepository) EXPECT() *MockReminderRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReminderRepository) Create(ctx context.Context, reminder domain.Reminder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, reminder)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReminderRepositoryMockRecorder) Create(ctx, reminder interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReminderRepository)(nil).Create), ctx, reminder)
}

// GetReminder mocks base method.
func (m *MockReminderRepository) GetReminder(ctx context.Context, reminderId string) (domain.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReminder", ctx, reminderId)
	ret0, _ := ret[0].(domain.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReminder indicates an expected call of GetReminder.
func (mr *MockReminderRepositoryMockRecorder) GetReminder(ctx, reminderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReminder", reflect.TypeOf((*MockReminderRepository)(nil).GetReminder), ctx, reminderId)
}

// GetReminders mocks base method.
func (m *MockReminderRepository) GetReminders(ctx context.Context, userId, status string) ([]domain.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReminders", ctx, userId, status)
	ret0, _ := ret[0].([]domain.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReminders indicates an expected call of GetReminders.
func (mr *MockReminderRepositoryMockRecorder) GetReminders(ctx, userId, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReminders", reflect.TypeOf((*MockReminderRepository)(nil).GetReminders), ctx, userId, status)
}
