// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/google_sign_in_usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGoogleSignInUsecase is a mock of GoogleSignInUsecase interface.
type MockGoogleSignInUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGoogleSignInUsecaseMockRecorder
}

// MockGoogleSignInUsecaseMockRecorder is the mock recorder for MockGoogleSignInUsecase.
type MockGoogleSignInUsecaseMockRecorder struct {
	mock *MockGoogleSignInUsecase
}

// NewMockGoogleSignInUsecase creates a new mock instance.
func NewMockGoogleSignInUsecase(ctrl *gomock.Controller) *MockGoogleSignInUsecase {
	mock := &MockGoogleSignInUsecase{ctrl: ctrl}
	mock.recorder = &MockGoogleSignInUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoogleSignInUsecase) EXPECT() *MockGoogleSignInUsecaseMockRecorder {
	return m.recorder
}

// GoogleSignIn mocks base method.
func (m *MockGoogleSignInUsecase) GoogleSignIn(ctx context.Context, idToken string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GoogleSignIn", ctx, idToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GoogleSignIn indicates an expected call of GoogleSignIn.
func (mr *MockGoogleSignInUsecaseMockRecorder) GoogleSignIn(ctx, idToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GoogleSignIn", reflect.TypeOf((*MockGoogleSignInUsecase)(nil).GoogleSignIn), ctx, idToken)
}
