// Code generated by MockGen. DO NOT EDIT.
// Source: shared/time/provider.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockRealTimeProvider is a mock of RealTimeProvider interface.
type MockRealTimeProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRealTimeProviderMockRecorder
}

// MockRealTimeProviderMockRecorder is the mock recorder for MockRealTimeProvider.
type MockRealTimeProviderMockRecorder struct {
	mock *MockRealTimeProvider
}

// NewMockRealTimeProvider creates a new mock instance.
func NewMockRealTimeProvider(ctrl *gomock.Controller) *MockRealTimeProvider {
	mock := &MockRealTimeProvider{ctrl: ctrl}
	mock.recorder = &MockRealTimeProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRealTimeProvider) EXPECT() *MockRealTimeProviderMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockRealTimeProvider) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockRealTimeProviderMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockRealTimeProvider)(nil).Now))
}
