// Code generated by MockGen. DO NOT EDIT.
// Source: feature/reminder/usecase/reminder_usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/MapMinder/mapminder_backend/feature/reminder/domain"
	dto "github.com/MapMinder/mapminder_backend/feature/reminder/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockReminderUsecase is a mock of ReminderUsecase interface.
type MockReminderUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockReminderUsecaseMockRecorder
}

// MockReminderUsecaseMockRecorder is the mock recorder for MockReminderUsecase.
type MockReminderUsecaseMockRecorder struct {
	mock *MockReminderUsecase
}

// NewMockReminderUsecase creates a new mock instance.
func NewMockReminderUsecase(ctrl *gomock.Controller) *MockReminderUsecase {
	mock := &MockReminderUsecase{ctrl: ctrl}
	mock.recorder = &MockReminderUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReminderUsecase) EXPECT() *MockReminderUsecaseMockRecorder {
	return m.recorder
}

// CreateReminder mocks base method.
func (m *MockReminderUsecase) CreateReminder(ctx context.Context, params dto.Reminder) (domain.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReminder", ctx, params)
	ret0, _ := ret[0].(domain.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReminder indicates an expected call of CreateReminder.
func (mr *MockReminderUsecaseMockRecorder) CreateReminder(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReminder", reflect.TypeOf((*MockReminderUsecase)(nil).CreateReminder), ctx, params)
}

// DeleteReminder mocks base method.
func (m *MockReminderUsecase) DeleteReminder(ctx context.Context, reminderId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReminder", ctx, reminderId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReminder indicates an expected call of DeleteReminder.
func (mr *MockReminderUsecaseMockRecorder) DeleteReminder(ctx, reminderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReminder", reflect.TypeOf((*MockReminderUsecase)(nil).DeleteReminder), ctx, reminderId)
}

// GetReminder mocks base method.
func (m *MockReminderUsecase) GetReminder(ctx context.Context, reminderId string) (domain.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReminder", ctx, reminderId)
	ret0, _ := ret[0].(domain.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReminder indicates an expected call of GetReminder.
func (mr *MockReminderUsecaseMockRecorder) GetReminder(ctx, reminderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReminder", reflect.TypeOf((*MockReminderUsecase)(nil).GetReminder), ctx, reminderId)
}

// GetReminders mocks base method.
func (m *MockReminderUsecase) GetReminders(ctx context.Context, status string) ([]domain.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReminders", ctx, status)
	ret0, _ := ret[0].([]domain.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReminders indicates an expected call of GetReminders.
func (mr *MockReminderUsecaseMockRecorder) GetReminders(ctx, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReminders", reflect.TypeOf((*MockReminderUsecase)(nil).GetReminders), ctx, status)
}

// UpdateLastTriggeredAt mocks base method.
func (m *MockReminderUsecase) UpdateLastTriggeredAt(ctx context.Context, reminderId string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastTriggeredAt", ctx, reminderId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLastTriggeredAt indicates an expected call of UpdateLastTriggeredAt.
func (mr *MockReminderUsecaseMockRecorder) UpdateLastTriggeredAt(ctx, reminderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastTriggeredAt", reflect.TypeOf((*MockReminderUsecase)(nil).UpdateLastTriggeredAt), ctx, reminderId)
}

// UpdateReminder mocks base method.
func (m *MockReminderUsecase) UpdateReminder(ctx context.Context, reminderId string, reminder dto.UpdateReminder) (domain.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReminder", ctx, reminderId, reminder)
	ret0, _ := ret[0].(domain.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateReminder indicates an expected call of UpdateReminder.
func (mr *MockReminderUsecaseMockRecorder) UpdateReminder(ctx, reminderId, reminder interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReminder", reflect.TypeOf((*MockReminderUsecase)(nil).UpdateReminder), ctx, reminderId, reminder)
}
