// Code generated by MockGen. DO NOT EDIT.
// Source: feature/reminder/usecase/reminder_usecase.go

// Package mock_usecase is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/MapMinder/mapminder_backend/feature/reminder/domain"
	dto "github.com/MapMinder/mapminder_backend/feature/reminder/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockReminderUsecase is a mock of ReminderUsecase interface.
type MockReminderUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockReminderUsecaseMockRecorder
}

// MockReminderUsecaseMockRecorder is the mock recorder for MockReminderUsecase.
type MockReminderUsecaseMockRecorder struct {
	mock *MockReminderUsecase
}

// NewMockReminderUsecase creates a new mock instance.
func NewMockReminderUsecase(ctrl *gomock.Controller) *MockReminderUsecase {
	mock := &MockReminderUsecase{ctrl: ctrl}
	mock.recorder = &MockReminderUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReminderUsecase) EXPECT() *MockReminderUsecaseMockRecorder {
	return m.recorder
}

// CreateReminder mocks base method.
func (m *MockReminderUsecase) CreateReminder(ctx context.Context, params dto.Reminder) (domain.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReminder", ctx, params)
	ret0, _ := ret[0].(domain.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReminder indicates an expected call of CreateReminder.
func (mr *MockReminderUsecaseMockRecorder) CreateReminder(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReminder", reflect.TypeOf((*MockReminderUsecase)(nil).CreateReminder), ctx, params)
}

// GetReminder mocks base method.
func (m *MockReminderUsecase) GetReminder(ctx context.Context, reminderId string) (domain.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReminder", ctx, reminderId)
	ret0, _ := ret[0].(domain.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReminder indicates an expected call of GetReminder.
func (mr *MockReminderUsecaseMockRecorder) GetReminder(ctx, reminderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReminder", reflect.TypeOf((*MockReminderUsecase)(nil).GetReminder), ctx, reminderId)
}
