// Code generated by MockGen. DO NOT EDIT.
// Source: shared/uuid_manager/manager.go

// Package mock_uuidgenerator is a generated GoMock package.
package mock_uuidgenerator

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUUIDManager is a mock of UUIDManager interface.
type MockUUIDManager struct {
	ctrl     *gomock.Controller
	recorder *MockUUIDManagerMockRecorder
}

// MockUUIDManagerMockRecorder is the mock recorder for MockUUIDManager.
type MockUUIDManagerMockRecorder struct {
	mock *MockUUIDManager
}

// NewMockUUIDManager creates a new mock instance.
func NewMockUUIDManager(ctrl *gomock.Controller) *MockUUIDManager {
	mock := &MockUUIDManager{ctrl: ctrl}
	mock.recorder = &MockUUIDManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUUIDManager) EXPECT() *MockUUIDManagerMockRecorder {
	return m.recorder
}

// NewV7 mocks base method.
func (m *MockUUIDManager) NewV7() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewV7")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewV7 indicates an expected call of NewV7.
func (mr *MockUUIDManagerMockRecorder) NewV7() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewV7", reflect.TypeOf((*MockUUIDManager)(nil).NewV7))
}
